### ISSUE TITLE
../../../../coines.mk: No such file or directory

### ISSUE THREAD

**Issue by Gfast2** [boschsensortec/BME68x-Sensor-API#1]
Hi Folks,

Very glade to bought 2x BME680 example. Since I'm planning to run BME680 on my Jetson Nano Devkit.I've really push my self to understand the driver code. But so far without luck.

The official [BME680_driver](https://github.com/BoschSensortec/BME680_driver) seems won't work without bsec library. Since I'm pretty newbie still. I just wounder how to get a handy start point with this sensor.

I've tried to test "forced_mode" in this repo with `make` command. But only get the error log as title above mentioned. I'm reaching the interest to figure out way to use these awesome drivers. Could any one help out?

**Comment by BoschSensortec** [comment]
Hi @Gfast2 , 

Let us look into this and get back to you.

**Comment by letrthong** [comment]
Hello All,
I try to build on  Ubuntu but  build error as below

```
thongle@thongle-virtual-machine:~/samba/BME68x-Sensor-API/examples/sequential_mode$ make  
Makefile:15: ../../../../coines.mk: No such file or directory
make: *** No rule to make target '../../../../coines.mk'.  Stop.
```
Do you have any update?

**Comment by Gfast2** [comment]
Hi @letrthong ,

I didn't have the chance to figure out the reason. Good news is that I've found another repo which give me the out of box experience I need on linux plattform: https://github.com/alexh-name/bsec_bme680_linux

**Comment by letrthong** [comment]
@Gfast2 ,
Thank  you for your information, actually ,  BME680 can work on  my board . below is result  which show off on web
Loại cảm biến: BME680
🌡Nhiệt độ (°C): 28.3
💧Độ ẩm (%): 78.8
🧘‍♂️Chất lượng không khí (IAQI): 198.1 (Ô nhiễm)
🧭Áp suất (Pa): 100603.0
 ☁️CO2(ppm): 1000.6

Currently,  I want to build BME688 to  detect smell  is coffee or not.
Now I am building sourc "BSEC_2.0.6.1_Generic_Release_04302021" ( Go to https://www.bosch-sensortec.com/software-tools/software/bme688-software/  to download )
if porting bme688 successfully, I will share them

**Comment by letrthong** [comment]
@BoschSensortec ,
Do we run one source code from  bme68x.h for both BME680 and BME688 ?

**Comment by philippludwig** [comment]
@BoschSensortec Any update on this? This is not the only file that is missing; another file, `coines.h`, is missing as well.

**Comment by juergs** [comment]
https://www.bosch-sensortec.com/software-tools/tools/coines/

**Comment by philippludwig** [comment]
@juergs Thanks, but this seems to be either outdated or too new, as it does not compile with the examples stored in this repository:

```
../common/common.c:34:12: error: too few arguments to function ‘coines_read_i2c’
   34 |     return coines_read_i2c(dev_addr, reg_addr, reg_data, (uint16_t)len);
```

(among other errors)

**Comment by philippludwig** [comment]
@juergs Thanks, but that link does not cut it. The functions are already implemented in `common.c`, therefore defining them again would just cause additional errors. Furthermore, these errors are not covered by the forum post at all:

```
../common/common.c:64:12: error: too few arguments to function ‘coines_write_spi’
   64 |     return coines_write_spi(dev_addr, reg_addr, (uint8_t *)reg_data, (uint16_t)len);
      |            ^~~~~~~~~~~~~~~~
In file included from ../common/common.c:12:
../../../../coines-api/coines.h:664:8: note: declared here
  664 | int8_t coines_write_spi(enum coines_spi_bus bus, uint8_t dev_addr, uint8_t reg_addr, uint8_t *reg_data, uint16_t count);
      |        ^~~~~~~~~~~~~~~~
../common/common.c: In function ‘bme68x_interface_init’:
../common/common.c:114:26: error: too few arguments to function ‘coines_open_comm_intf’
  114 |         int16_t result = coines_open_comm_intf(COINES_COMM_INTF_USB);
```

It seems to me that the examples in this repository require some custom-modified version of this "coines" library.

**Comment by BoschSensortec** [comment]
> 

Hi @philippludwig , the common file wasn't updated to support the latest interface changes in COINES. Updated the common.c file now in the examples to reflect the needed changes. Can you confirm that is works with the new changes?

**Comment by philippludwig** [comment]
@BoschSensortec Yes, the examples now compile without issues, thanks.
