### ISSUE TITLE
BME68X_CHIP_ID is 0x60

### ISSUE THREAD

**Issue by chegewara** [BoschSensortec/BME68x-Sensor-API#12]
I am working with BME688 and begin does not pass this line, because my chip is reporting ID 0x60:
https://github.com/BoschSensortec/BME68x-Sensor-API/blob/master/bme68x.c#L154

I would like to ask if this is variation or i need to know something else about my chip?

Thanks

**Comment by horazont** [comment]
0x60 is what BME280 chips claim, are you sure you have a BME688?

**Comment by Murmele** [comment]
@horazont 
We bought the module from: https://www.reichelt.de/de/de/entwicklerboards-sensor-bosch-bme688-debo-sens-bme688-p306628.html?trstct=pos_3&nbc=1&&r=1

and in our case the chip id is also 0x60 and not 0x61 as in the datasheet

**Comment by BST-Github-Admin** [comment]
@Murmele , it seems the manufacturer of the board has used the wrong part. Kindly check with the manufacturer or distributor.

**Comment by Murmele** [comment]
@BST-Github-Admin thanks for the clarification!
