### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Miliks** [boschsensortec/BME68x-Sensor-API#20]
I-m running the bmerawdata.py file on Raspberry Pi 400 and after increasing the stack size to 32768 and setting core file size to unlimited i-m able to run the measurements for around 40 times and then it go to Segmentation fault without generating any file. Is there anything i can change in configuration to make it work?

**Comment by BST-Github-Admin** [comment]
Hi @Miliks , Please report your issue on the community page : https://community.bosch-sensortec.com/t5/Bosch-Sensortec-Community/ct-p/bst_community
