### ISSUE TITLE
BME688 parallel mode data read out

### ISSUE THREAD

**Issue by jk0010** [boschsensortec/BME68x-Sensor-API#22]
Hello,

I am working with a BME688 in parallel mode. What is the correct way to read the status bits (new_data, gas_valid_r, and heat_stab_r). I've implemented this method below, its similar to how the API implements parallel mode.

```
read all 3 data fields

//repeat this for each field
if(new data && gas valid && heat stab) //each must be 1
{
    print data
}

```
 

As a result of this I was getting an ODR of about 0.1Hz. I loaded up the same sensor configuration in the Bosch Development Desktop GUI software and was getting an ODR of about 24Hz. Any suggestions as to how to properly read status bits before data registers on the bme688 in parallel mode?

**Comment by msloth** [comment]
Forced mode, I poll the status reg and check for new data, then read it out.

Parallel mode, I loop a polling for new data and inspect the data returned. If new, and index is not previously seen, I store this data. When all profile indices are filled, I stop the sensor. Note that the chip only stores data from 3 indices, and the get_new function can also only handle 3 datas, so if your profile is >3 steps you need to loop over. This took a long time to understand, the examples were not just not helping, they are actively misleading since you get the impression that you just wait and then read all the data out. Not so.

Hope this helps.

**Comment by jk0010** [comment]
Hi msloth,
I'm going through the API and looking at the function `sort_sensor_data` which seems to be explaining what you are saying above. I'm going to need to take some time to understand this. Thanks for your help, greatly appreciated!

**Comment by jk0010** [comment]
Hi msloth,
I'm going through the API and looking at the function `sort_sensor_data` which seems to be explaining what you are saying above. I'm going to need to take some time to understand this. Thanks for your help, greatly appreciated!

**Comment by jk0010** [comment]
Hi msloth,
I'm going through the API and looking at the function `sort_sensor_data` which seems to be explaining what you are saying above. I'm going to need to take some time to understand this. Thanks for your help, greatly appreciated!

**Comment by jk0010** [comment]
Msloth, do you have any example or repo that would be of use here?

**Comment by msloth** [comment]
Sorry, nothing I can publish, just proprietary stuff. But I can help if you have any questions. I hate that I had to reverse engineer the driver to understand how to use it. The examples are not good, and imo misleading.

IIRC `sort` basically just ensures that when you `get_data`, the data read out from the chip is inserted in the `bme_output` array is in order. You see, the chip has 3 sample storage slots, used in a rolling window style. So when the Bosch driver reads it out in the middle of a profile, it may be read out as (profile index) 8, 6, 7. Bosch `sort` then parses that and fills it out in the array as 6, 7, 8.

But the key understanding is this, that the chip has 3 slots, and the Bosch driver does not do any caching, staggered read out, or anything else. It just reads those out, and sort it per above. It's up to you to keep polling `get_data` and store everything new until your profile reading is complete.

**Comment by jk0010** [comment]
Ok, thanks for your help, becoming more clear. I found another implementation of this API with zephyr which is what I'm using, that helped as well. I found that in the "coines.h file missing" issue on this repo.

Thanks again
